import pandas as pd
data='''>Rosalind_2350
AACTTAACTAGCTGAACTGCGTGACTCTGAAGCATAACTCCCGCTATTGGACATGACTAA
TGGTGAAGACTACTGTTTAGTGCCATTACCGGCAACCTTTTCTACATCGACAGAGTAGAG
AATTCCTAGCTTCCGGTTTAGGAGGTGTGGCCGGGCCCTAAGAGCTATGTCAGTCGATCT
ACATGCATTATAGATTTTGCCGACTCATTAGTTGAGTTCCTACCGAGCGTCATAGACGTC
TCTATCATTACCTATCGCAACGCCTTACCACTAATTGTCTTGCTGTGTAAGAACCGCTGA
AATCGGTCATTCTAGTCCTGGGACACAGCTCATGCGAGGCTTGTTTCGGGTAATTGCTGA
AGTGAGGTGCAAGAGCATCTCCACTCTAGTTAAACTAGGTGGCTGAACCCACATAGTTAA
TTTGCTGTCTTCTCGACGACAGGAGTAAGGTTTTTCCCTTCCTCTAACGTAGCGGGTGAG
ATAACTAAACCTGAAGCCTAGTAGTGTCACGAACTACAGGAGCTTGGCAGTTCGGCCCGG
GTATCACCAGTCCGTGTCCGCGGTACCTCCGTGGCCTCTCACTGGAGGTCCGTCCGTTCG
TCGATACACTGACTTGGTCGAAAACGCGCTTAGTGTGACTGCAATCACAGTTAATACCGC
CGGGAACCGCCACGGTTTTTTCCCTGAGGCGGTGAGTCCCGATATCGTTATATCGTGTGG
TAGTAGAGCTAATATAACACCCGCCAAAATCAGCAGAAGGTGAGCACCACTCCACCCTAC
TTCCGTCGGCGTGATCGCATCTGGGTATCCATAATGCGGTAAGCAAATGAAGAGTCTGGC
AGACTTCGTTCGCGTTTACATTCAGCGCAGCTTCGAGAACCATCAAGTTGTGCCTCCTGA
AC
>Rosalind_2016
ACGTGGTTAAAGATCGACCTCCACTAATAGACTTCTGGCGCTTAGATCCAGATAGTCTAG
CCTCTCCCGAGCCTAGGTTGGCACATATCTAGCTAAAACCCGACGAGCCAGGTACAGGCC
CCAACTATGTCGTCTAAGAGTTATACAGTGCAGCGATCCGAGAATGGTTTAAACGACGTA
GACTCACAAGCAAACTGCAGCTTTGGTGCCAAGCTTCCTCCAGACGTGGCCACCGAGGTC
CCCTAGCGCTTTTGTTTAAATTTTGCCCAGAGGTGAATATGATCGGGGACTCCTCTGAGG
CCGCATACGCCAAGCCTACATTGTGGGAGTGGCGTGTACGCGGGATAAGGCGAGTGTTGT
TCTTGGCATTCATATGCCTGTATACGTGGTTTATCGCATTGAGTTCTTCACGTTCTCTAA
AGAATGTACACTCGGTTTACGAACAGTTGCTAATAGGTAATACTTCTTTCGAGTAGGTTA
CGTATAATATAAGTCTCCGCCCCACAACTTTGCAGGTCTCTGGGATGGAGTTTCTTTCGT
CGACTTCATTCTCATTTGTCGAGAAAAGGGCTAACATATCACGCGGGTATCGCCAGCCAT
CCCGCAATAATCTTGACGATGACCTCGTCAGCTTTGTTAGTACATGCACTCGGTGGATAT
CCTATCACAAGAGTAAGTGCCCTTTGTATCCTCAAGGAAGATTCGTAAGAGCCCGGGCGT
ACGCATCACCTCCATTTAGCTCTTATAACGTTTCACAACCGTCTGCTTATTATGCGGTTA
TCTCAATTCCGTAGACTAGTATAGAGAGATTTTTAAACGACACAAGGGCTCAAGCACCCG
ATCAGGAAGCTCAGAAGACTTCGTTGAAGAGGTTCATCATGGTCCTTAGACTGCACGGCA
AA
>Rosalind_7176
TCTGCATGATTACGAGTTACTACGAATCCAGCCCTTCGAGAAGAGCAGTTCGTGCCCCCC
CGTACTTACATTGTTCTTACTCGCTGTTGTGGTACCCATTCGTTTCGGATTTGGTACGGG
ACCTTACTGTCAGCGATCCCGGGCCGGAAACCCCCACGGACCTTCTAACACCTAGTCAGC
GCTTGTCGATCACCAATCATTACACCGTTTGGATGCGAAATCAAGGTAAGGTTGCTGGGA
GTCTCACTGATTCGACTGACGCTCTAACCTCTTGCGGTGTGTGTACCACTATATACGATA
CGTTCACGTCGATGTGCTAGTGTGAATCGAACAATATTAGCGTTGCTCAGTGTGAGGCAC
GGTTAAAACGTACATCGCCCGCTAGCAGGTCGCTGCAGACATGTTATACCAAATAGGATC
TGCATAAAACGCAGAGCTGACAATAAAAGCCACCACATATCATCGCGCACCTCCTTTGCC
GATCCTCCCAGCTCATCGCTCTGCTTGACCGGTGTGGGAACAGCGCTGATAGTGGATCAT
CGCTGTATGTTTTGGGCGTTATACGGACGTTCTGGTACTATCGTGAATGGTGCTTTTAAA
TGTGAGCTCCAGACAACGCGACGGCGGCTGTTTTGTAGTGACTATCCGTCATCACATCTC
TGAGACCGCTATTGCACATTATGCGTCCCAAGACCTCCTCGTATCTACAACCTCGACATG
AGATCTATAGCCGTCTAAGCATGAAAAGAGCACTACCACCAGTACATTCCTACAGCGGTT
TAATCTGAATGGCTGGGTTAAAATCCCGTTAGCTAAGAGAGGTACACCCATCTAGTTTTT
TTTCATCATGGTTCCCCTACCCGCCTTGCACTGTTCCGTGCTATGCAGGGTACCATGCAT
AC
>Rosalind_3642
GTGGTCGCTACGAGACTAATGCCATGCGTCTTGTTGACGATGATACGGCCAGGCATGAGT
ATTGATTCCCAACACTGATCGGCGCGACGGTCCTAAGCGGTAAGATCATTAAGCGGTATT
CCACTCTTCGCTAACCCAGCTAGATATCAAATGCGTCCGGCTGATATTCTAATCATCATT
GCACCTCTCCCACTTGGAACCTGTATCGAAGCGAGCCTAGTAACCCCGCGACCATCGGTG
CAGCCATCTTGTATCGGAAACGCGACATAACATGATGCATAAATAGTCTACCTATTGAAG
TGGCCAACGAAATCTTCGGCCCTCGTATGTCTGTGATCTGGCCTGCGCTTTAGGATCGAT
TTAGTAGAAAGCGGCACCCATTTTTGAGCCGCGGAATGACCACAGATGCCGCCAAAGAGA
CGTCTAGTATGATATGATCGAGGTTAAACTTATGCGCACGCGCTAATTGCTCTCCCCTCG
TTGCTTCAACCCCATCAAGGCCCCACGCATTCCCCACGGGGCGCGGGGATAATAGAAAAC
GTAGGGAGCGGATATGGCTGATATACCTTGCGAACACTGGTATAGACAATGGCGAGTAAA
ACACCGTGCGCGTTCAGATGGTTAGGCCGCCACACGCCAATGCCAGCCTACCCCTCGGTT
AGCTCTAATTACTCTATATTGAACGAGTTGTTACCTCCGTGTTCCTTTCTACGTGTCGGT
GAGGGATTACTGACCCAAGCTTTGGAGGTCCTTGGCTGAGGGAGACTAAATGGACCCTCC
GTACTTCACTGATGGCTTACTTTATCGCGTTTTGGGGCGTCGGCAGCTAACCCGAACGTT
TTTTGCTCTTAGCATTTTAAGCCTAGCCATCCAATAGATTAGGATGGGGCACATGCGTTT
AC
>Rosalind_6440
AATAGGTAGTGCAGGCCTTCCATGGACACGAACGTGCATCAGAGTGTCTGCGCAAACAGT
TCTATCCTGATCAGTGTCTTCGTAAGAAGTAGCCCTCCAGTAGGGAGTGACAAGATGAGT
TAAGAGGTTTAACGAGAAAACTAATTCCGCCAGCGATAGCATGGCAAGCATAAAAGTACT
TATCGCGGCCGTATAAACGTTTAACCTTGACCCTTAAACCCAGATTCTTTTATGGCGCCG
TAATCCTGTGACTATTAGTGCCAGGGCCAGGTCAGTCCGCCGAGTCATCACCAGTATAGC
TTGGGAGCGTATTTCTCATCTTTAATCTCGGTCACTGTGTACATTTCGTAACCATCCCGC
CCCGATGGTCTCGTAACAGGATCGTTGCCGGTCGAGTTCCTTAGATAGGCGTGAAAATGG
ACGCGGGCTAAGTTTTCTTGAGAAGCGGTGAGAGGTCATAATTCTCGCGGGGTTTCGATA
TCCATACCCAGGGACCTAAGTTAGCTTCAGCACTGATTATTCCGACGAGTGGGGGCTAGC
CTATCCTTTCCCCGCCTGCGTGTTGCCTTGCTTTTGACGAGCCAAAAGGCTTGAGTTCAC
TGGGTCATCCGGTGGTAACGCGGCGTAATTCAGGCTCGTCCCGCTTGTGTATGCCCTGCC
TTGTGTCCCATATATCCGTTTCAGTCTAGTCAATCTCCGTGGGATACGGTGAGTATTAGT
TCAAGCTAGGTAAGCGCATGAGGCTTTGAAGTATATTGGAAACTGCTCCTCACGTGGTAC
GTTTATTCAGGTGAGAAATATAACAGGAACACACATGACTACAATTTGTGACTGCAGCAA
GCCGGCGAAGAGCCTGCCATCTGGTAGTCAGCCTCTTACCCCGTGCAGCTTGGACCTCAG
GT
>Rosalind_2362
CCCGGCTGTCCGCGAGAAAAATACATCGGTACCGAACTCCAAAATGAAGAACTCGGGGCG
ACAACTGTCCAAGTGGATATCCCAGCGCCGTGCTCACCTGGGTTAGGCAGGAGCGCTAGC
GACGAACGCCGGGGTACTGGAGACATCTTGTGCGGGAACCTGGGAGCCACAATCACACTC
ATTGTCTACCTATGCCGCATATCTTTCCTAAGAATGGGTAAGTTACCTACGAGAACTGGT
AGACTGAGCCTGAGCCGTCGGAAGCCTACCATAGGTGTTTAACCTTCTCTGTTGCATAGG
TGCTCGTGTTTCCGGATGTACTCCGGGATGACGGGCTCCCATGGACGACGCCGGCTATAC
TGTGATGTATTTATCAGTGTCCTGGTTTCACAATTCTAAGGCCAAGTTCCCAAGGACCGA
TGACACGAGGAACAAAAGAGGGACGGACCGGACGGACGAGACGAAGGGCGGACTGACCAG
AAAAGCTCAAGAAAAGACCTACAGGAGTGCGCAGGTGCCACCTACAGAGACGGGCAGACC
TGATTCATTGTTAGTCTCGGGGTAAAGACTTTGTACCCGAAAAATGTATCAGGGTGAACT
GTCGAGGAGTGAGCCCAGCTCCTGAGCAGAGTTCGAATCTAGATCCCCGTCACCCGACGA
ACGCTCAAAGCTATCGGGTCATCGCTAGTTCAACAAGTTTGGCCGCGAGCGAGTTGTCAG
GTGTAACCATAACCTTAACGGCATCTTTTATCAAAATTAGAGCATATCGCCCCTCAATAT
GCACTGTCCTCGAATCGCCGTGTACGACAAACTCACGGTCTATATCTCCTTGGCTATCTT
ACACGGGCAACACTTTGACGAAGCCTAGGGTAATTCCCTTGAATATACCTCAAGTGCACC
GC
>Rosalind_3579
TTTAGCGAATTGGCCTTGCAACGGAGATGGATCTGGATTGGAGAGCGTCGATGTTCACGG
GCAGGGCTCGCCAGACCTGATGTGGAGCTTTTCTAGGGTATACAGACTGATCCTCTGCTT
GCTACCGTAACAGCGGGGGGTGACTCGCGGACATTCGCTTTCAAAAATGTAAATACGCTG
ACGGCACGAAAAAACCAGAATCAAGAAAGTGCCTGTGGGGTAGAAATGCATAACGAGTGC
GGACGGATAGTGCGCGGGTGCTGACCCGTCGTCCCAAGAAAAACGTCCTGTAACGTCCTT
GATAGGTATGTTATGACCATCAAGCAGAACCTATAGGAGAGTCCGCGGACGCTCATAACC
AGACCCTCCTATCGTAACGCTGATCATGCGGGGCGGCGTCCATGCCTACGATACCGGGTT
TAATACGCGTTGACACTACGACTGACTTAGCTAACATTTTCTTATTGTGGCGATACACAC
TTCCGCCCTTTCGCTTTCCCACATACAATGAAGAACGGCTGTCAAGCTAACAACTTCAAC
GCCGGTATCCGTCGGATTATTAGTACGCAAGTCGAAATTGTCTGGGAGGGGGTCGGCCGT
TAGTTGAGGCGCTCACATGGCCGCGTAAACAGGCGCCATAGTATGGTGTTTGTCCAGTTC
GCAAGAAGCTCATCACAAACGAAACGAGTTGCCGGTAAAGGGACATCCCCGGGACAGTTC
AATAACCCGGACTCTACGCTAACCGAAAGGGCCAACTGGGCTCATCGCAGCTATGATACG
CGGCGTAGGGCAGCCGCCAGGAGTCCTAGCTCTCGGCCGCTCGCCACTCCGGGTTATGGG
CTTCCGGTCCCTGCTCAAGACAGCCGCTGCGGGCGGCCGACTGGGACAGTGACAACCTCT
GA
>Rosalind_5963
AGGGTGGTAAACGGCAATTTCGATGATGTCCAGACCGAGTCAAGCCGCCCGACCTTAAAA
TGCCAGAGATGATCTGCCGTTAAGCGCCACAGCTGATCCCACTGACTCACTAATGCCCTA
CAAAATTACATCTATGGTTAGAATCTGTCCCTAAAAGCTTCACATATTCAAACTTGAGTG
TACTTAACTTGAAAGCGTCCAAAATGAGTCCCACTACCTCCGGAAGACCACGTCTTCTTG
AAGCTAGTCTATATCCACACAGCCCCCGGTATCAGAAATTCCATTAAACGCACATCCTGT
GCAGCCTCCCTTTAGGCCCGGACATCTCGCGCAATGTGTTCAAAGGACCCATGACGGAGT
GAACATTTCTGACATATCCCTGTGTAAGGCCGCGGCGGGACCCATTCTTTTTACAAATGA
CAATGGATGCCTGTGTCTTGGAGAGATGGCCTGTTCCGGTATCTTAGTTGCTTATAACAG
ATTTCCGGGGCGTCACTTATCTCGTATCAAGAGTCGGAGATTGTAGATATATGGTCCTCC
CTATATGGCCTTCACGTGTGCGTAGTCTGCCGCCTGGGTAGAATAGGAAGAACTAACGCC
CACTTCGTGCGTATGACGAAAGGGGAAGTGATAGCGTCGCTAGCGCAAGACAGGTCAGGA
CGAGGGTGGCGGTTTTAAAACTCGATACCCGCCATACAGGCGTTCAACGTATAAGTCTAC
GCCGACCGATTGGTCGCACAGGGACTGTAGCTCCGTTGAGGTCGCTGTCTGGATTGGCTC
GCCCTCGGCGGATTGGGCTTCTCGGCGTCCCTCCTAACCAACATCCCTGTACCTCTTGGA
AGGTGAGAGACTGATATAAGATTTGTATACGAAATAACAACAGGAGCGTGTGAGTCGGCG
CC
>Rosalind_5329
ATGATGGATGGATGTGAGGCTGGCGACGTGAAACAACGTTCTATGCAGGTTCGTCGGCTC
CGTGAGTGGATAACACTACCAACTAGATAGGGGAATATCAATTAGCAACTGCCTATGAAG
CGATGCACCGTCTCTTATTATTATACCGCATTGAAGCATGTTGGACCAGAAGCCTCCTAG
CAACGAGAAGCTGGATGCGGCCGCTTTTCTCATATAATCTCAATGTCGGGCAGTCGGAAT
TCAGACTACGAGTTTGGGCGAGATCTAGGATAAAACCACCTCCTCTGGTGGGTTTTCACC
ACCCGTTTAGACGCATGTTGTATGTGCTCCTGTGCACCTCTCGTCCGCCATCTGAACCGT
CGACACCAGAGCGTAACCGGCAAGCACAGCCTCAGACCTGTTTAAATCTCAGGGGAATGT
GGCAGGTGGTGTTTCCCTTATCCCCGGGTTATGTCACGAGTCTTAACCACCCTGCAATTG
GCACACGGACCGGAACCTACCGAAGACTGTGGTCCAGTTAACGAGATAGCGATCCGCAAT
TGACGTTCTACGAGTCATGATTCGAGGGCAAAATGTCACGACTCTAGCTTTGTCTGGATA
TAGACGCCTCGGATCTCAGGGATGTCGGGTGTGACTAATCCTAAAGAGACCTCCATTCTT
TAGGTCTAGTGTTTCACGTTGTCTGCTGCCGGTGAAGGGCCTGACATGCTCCACCCTACA
AAGGGCCTGTCATGATACCTAGCTCTAATGTGGTCCAATCCCACGTCCGATGATATACGG
ACTTAGCAGCGCTTCATACTGCCGCTGTCGTTGCTATGTCTACCCAAGCTCAAGACGTGA
GCTATTGTGCTAGGACTCCCGTGGATGGTTTAATACGGAATCGATATTTAAGGCACCCTG
AA
>Rosalind_5551
CTAACTGCAGCCAGCAAGCACGATCCTGGTGTCCAAATCAAACCCCGGTTGGAGACTGGA
CCTTGATCGCGAACTAGCATGATAAGTGAGGGGAGTTTTTACCAGCTCTAATTGCGCTAT
TGCTCTTTTTCTCTGTAAAACGCGTTCGCCATGCTAATATATCATGGTCCTCGCATACGC
GTAACTGCGTGCCGGTTCGCGACGGGAACCCGTGTATAGACATCAGAGCTCGCGCTGAGT
CTTACCGCGGAAGTCGGATATCGGGCCTGATCCTTCCAGCCTCATTGTGTTACACGACCG
CCGATATTAAAGCTGGTCGTACAACTGTGTATTGGCGTTTGAGGAGTATATACCCTGGTT
GGGAGGACCGACGCAGTTCACGCCCCTCACCTGTCCTTGCGCGACCTCGGTCAGCGCGCG
GAGCGCGGCAACTTTAGTATTCCGCTTGCCTGTGTGCTTACTCGTCTATGTGAATCCCGA
GTGAGTTACATACACTGCTGCTAGGGAACAACGACGGCAGCGATACACAATAATGTGATT
CCGATAACACTGGTTACCTTTAATAGCTCTGCATCTTTGTAAACCTGACTGCAATCCTGA
TTTGGTATCGTATCTATTAGTATGCTCAGCTCGTAGCAATAAGGACCGGACATATGTTGA
CGTAGCGCCGGTGTCCATCGTAGGGGATCATTATTTACGACGCGGGTGGTGCCAGCCTAA
ACACGATCACGTACGACCCAATTCGCGGCTGGGATTCGCAGGAGCCACTCGTCAGACTCG
GCTACACCTGGTTTCACCTTTTAGTCCTTCCACTCTATGATAGTACGCCTAGATAGAGAT
ACCAGAGGACTTTCCAGCAATTTGTCTTTGTGAACTAAGCGAATATTCAATACATCCATC
CA

'''
def solve_fasta(fasta_data):
    # FASTA rule: ek >ID ke baad ki saari lines milke ek poori DNA sequence banati hain
    sequences = []       # list of full DNA strings, ek per ID
    current_seq = ""

    lines = fasta_data.strip().split('\n')

    for line in lines:
        line = line.strip()
        if not line:
            continue                     # khali line skip
        if line.startswith('>'):
            if current_seq:              # pichli sequence save karo
                sequences.append(current_seq)
            current_seq = ""             # naye ID ke liye reset
        else:
            current_seq += line          # isi ID ki lines jodo

    if current_seq:                      # last sequence bhi save karo
        sequences.append(current_seq)

    n = len(sequences[0])               # ek DNA ki total length

    mat = pd.DataFrame(0, index=['A', 'C', 'G', 'T'], columns=range(n))
    consensus = ""

    for i in range(n):
        # column i par saari sequences ka character nikalo
        col_chars = [seq[i] for seq in sequences]
        counts = {b: col_chars.count(b) for b in "ACGT"}
        for idx, b in enumerate("ACGT"):
            mat.iloc[idx, i] = counts[b]
        consensus += max(counts, key=counts.get)

    return mat, consensus

# def pro(matric):
h,j=solve_fasta(data)
with open("dfhdf","w") as f:
    f.write(j + "\n")
    for base in ['A', 'C', 'G', 'T']:
        row_values = " ".join(str(v) for v in h.loc[base])
        f.write(f"{base}: {row_values}\n")

print(j)



   