def get_reverse_complement(dna_string):
    # 1. Create a translation table for the complements
    # 'A' becomes 'T', 'T' becomes 'A', 'C' becomes 'G', 'G' becomes 'C'
    translation_table = str.maketrans("ATCG", "TAGC")
    
    # 2. Translate the string to get the complement
    complement = dna_string.translate(translation_table)
    
    # 3. Reverse the string using slice notation [::-1]
    reverse_complement = complement[::-1]
    
    return reverse_complement

# --- Main execution ---
if __name__ == "__main__":
    # You can paste your dataset string here to test
    sample_dataset = "TGCGCACTGATTATGGATATACAACAGTTCCGTAGATTGTGTCAAGTAGATTGCTGGTTAGTCCGGGAAAGCGTCCATACCACACCAGAGGGGGGGCAAATAGTGACGGACAAGAGATATGCCCTAAACAGTAGCAACGGGCTTTCTGCAGAACCATTCACCGGTATGGACTACAGGGTCCTGCCGGCCCCTTGTTATGTTATGTCTCCAGGATGCACATATGCCCCGGGCCTTCGGCTCAGAAGCAGAGTCATGACAACCATCAGTCCGTACATCATCTAGGCACGCGGTGGTAATCGGGTTTGCACACTAGGACGGGCCTGGATTTAAGAGAGCATACAGGCTGGCCCAAGAAGCAGACCAGTCTGTCGGGTTCCCGTCGCGAACGGTCTAGGTGCGATTGGTAATAGACGTGTGGATTTTAAATACACACTCTTTGGATGTCAACGAGTTCATTCCGTAGACTAATTCGGGGGCAGCTTATGCGCTCGGAGGGTGTGTGATAGAAAAACCGAAGAAGCTACACGTCAGCCGCGCTTTTCAGAATGAGAGCAAGGCGTCAACTTTCGCCAGTAACGCTGTAAGGGCAGCTATACTTCGTGCGAGAGGCAACATGCGCTCCACCACAAACCGTCTGGGAGCCCTGACAGATACAAAATAGGAGCGTTCGGCACAGGTTCGATTCTCATGATGTATCCCTGCTACGTTTAGTGCCCGAGCTACGATTGGCCTACGGATCGGCGACGAGCTTCCGTGAATGCAAGTTACATATCTCGCGTGGCGAGCTATCTTTCCGCAGCCTTGTCGAGCTATTGTGGGGGGGTGAATGTGGCACAGGTGCCAGGAGCGTGAGTTATAAAAAGGTCCAAAGAGGCAAAAAGGAACT"

    
    # If you want to input it manually in the console, uncomment the line below:
    # sample_dataset = input("Enter your DNA string: ")

    result = get_reverse_complement(sample_dataset)
    print("Result:")
    print(result)