def calculate_gc_percentage(dna_sequence):
    """
    Ek simple function jo DNA string ka GC% return karega.
    Formula: (Count of G + C) / Total Length * 100
    """
    g_count = dna_sequence.count('G')
    c_count = dna_sequence.count('C')
    total_len = len(dna_sequence)
    
    if total_len == 0:
        return 0
    
    return ((g_count + c_count) / total_len) * 100

def solve_fasta(fasta_data):
    # Dictionary banayenge data store karne ke liye { 'Rosalind_123': 'ATGC...' }
    dna_dict = {}
    current_label = ""
    
    # String ko lines mein todte hain
    lines = fasta_data.strip().split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            continue # Khali line skip karo
            
        if line.startswith('>'):
            # Ye naya label/ID hai ('>' hata kar save karo)
            current_label = line[1:]
            dna_dict[current_label] = "" # Nayi entry shuru
        else:
            # Ye DNA sequence ka part hai, ise current label mein jod do
            dna_dict[current_label] += line

    # Ab sabse zyada GC content wala dhundte hain
    highest_gc = -1
    best_id = ""

    for label, sequence in dna_dict.items():
        gc_percent = calculate_gc_percentage(sequence)
        
        # Agar current wala sabse best hai, toh update karo
        if gc_percent > highest_gc:
            highest_gc = gc_percent
            best_id = label
            
    return best_id, highest_gc

# --- Main Execution ---
if __name__ == "__main__":
    # Yahan apna Rosalind ka data paste kar dena
    # (Maine sample data daal diya hai testing ke liye)
    dataset = """
>Rosalind_8847
AGATCGTTAGCCACATGCGATCGCGCGAGCACGGTCTCCAGCAACACGTGCCCCTAACAT
TGTTGCGCACTTTCGTGGTATTACCGAGACTCGTTCCTGATGGATCCAGGTGGGATGGTG
TGGCGAGCGTACACTCACTCTGACCTGTAAGCGGTCGAAAGTTTACCACGGTCATGACGT
TCTACCGTGGTAATCGCCCGACATCGCTACGCTTGTCGATTTGCTCGTCCGTACGGTCTG
TCAAACGGGAGTAAGGTTAAACTAGCGTGGACGATTCGTCCAGTATAATACACTGCAGGA
CATATCCTGACACCGGTTCAGATCCACGTCCAAGGGTAGTCCCTGGCGCCTACGAGTAGA
GGTTAAAGACGGTATCGCTTCTGTGGACCCTCGGGATAGCAATGAGACCCTTATAGCAGC
TATCAGTTAGTGTTTCTGACTGGGATAGCCATTCTCCAGTTCTAATACTAACTAAGCCAG
ATAGCGTGATGGTCAACCAGCAAAATATGTCTCACTCAATGGAGCTCGCCAGGATTAAGC
ATCTCGCCCGCAGACCGGGTACCGCGAAACCGTGGAGACATTTTTAGCCTCTTTTTCACA
CACAAGGTTAAACGCGCTGTAATCTCGATGAGGAAGTTTTGTTGTTTCCGTATTGATGAC
AAGATCAAAGCGTTCTATCTCATAAAGAGCACGCAATTCTGACGGAAGAGTGACGCATCA
GCACCCCTCGATCATCCGCCATCGCAAGGTTATGTGAAGTTCCGGGTCCGGTATGCCACT
TTTCTTCCTCCATGTACCATGTATTAATCTAATCTCCGGGCAATAGAAAATGAGTGGTCA
GCCCCCAACCATCGCGTAATTGTACTTTTCACTAGCTTGGCGTAAGAGCGTGGACGTGTG
TCACTATAACCGAATATCACCAACCGAGCGTAGACGACTAAGGACCGCTCAGTTGG
>Rosalind_0613
ATAACGCCTTACGGGGGCATGTCCGATCGACGGAAGATCTACAAAGTCACTTAGACCGTA
GTATACAGACTATGAGCGCTCTGGGTCATACACGTCAAATGCCTCAAAGATATTCTAGCC
ATCGTCGTTCAGCTCCGTCTCTAAAAACTGCTAGAGGATAAGGTGCGGAAAACTGGGCTT
CGGACCACCTGTACCGTAGCGACTATGTAGGGCTAGTCTTGACGAACTGCGAACTATAGC
AAATTTTTCACACAAGCAATCCGAGCCCTTTTGAAGGCCTTCCCGTACGCGCAATCCGCT
GAATGGCGCCGAAATGTACCCGACTCGCTCGTGAAGTTAACTTCTTTGCCCCGTGCTTTA
TTTGAGTTGGAGGTTTCCACCTAAGATAGTCGGCGCGTTTGATTTAATGCCCAAACGACT
GTTCGTTGGCTTACGTAATAACGACACTTATTAGATCGAGCGGTCTTACATCGACGTTCC
TGTTCTGTCCACCCGCCTATACGAGGATTTGCGGGCAAACATATGACAGTCCGGGCGGGA
AAGAGATAACATGAATGGGAGGGCACTCGCCACTAATAGTAAAACATCCAAAGCGGCTGC
AACCCTTATTTTTGCATTCCAATCTGCTCGTTGAATTGAGATCGAGTAGCAGCAGCATCT
TTTGAATTGGAGCCTCCCAAGAGTTAAATACCACGAAGGGCTAGCTTAATTTCGCTGCTA
CGGAACGGGTATGTATGTATGACGCTTCCGGGGGCTTGGTCAATAACTATTTCTTAGAGC
CTCTTATCCCACCAAGTATTTCATGATCTACTAGTCCCC
>Rosalind_7609
CCCTTCAGGATCCAGGATGACACTTCGGATCACGCGCTCATCGAGATCGAAAGGTCTTAA
ATAGCGCGACCTCGCATTTCCAACCACGAGGCCTGTAAGAACTTCTTCGTTTCAGCACAA
TCAACCGTTACACTATTATAGCCAGACTTCGGGCTTGGAGGCGCGGCATGGTATCGTAAC
GATATTGGACTGGTTCCTTACGTGATAAATGTCTATTAACAAGGTAGTTTACTTTCTGTG
GTTCACCTTTCTCCAAGTGACCAGGAAGGGGTCCCTCCGGTCGGTCTATTCATAGTCGAT
AAATCTTCAACTGGCATATGATCATCGTCAGTCTGATGCGCCTGACAATTATTTCGGTTA
TCGATTCTAGTGATCCAAGAAAGGCGTGAAAGTATCTAAACCTGGTGGGGCCTTCACTGA
CGTGGCTATTTATCGGTTGACGTATTCGACCGGGCGGGGGATAATTTCGGCTCCTACGAA
CACGCAAAAGTGGGCCGTTTGGTCTTACCATCCCCCAAGAGATAGCTGGTTTAAACGGTA
TAGACGTATCCCATGAATTTTTAGGCCGCTAAGGAACCACGCCTAGCTAGCCTTCTCGTA
GAGAAAGAGCAACACAAGGTTTCCAGCTGAACCTCTTAGGCCGCTCGCGTGCTCAATTGA
TGCGTTGCCCGCTGAAAGGTACTAAGACCTCTTTCCTCATAGTAAGCCCAGCGGATGCAA
CTGTTACTGATCACGGAGCCGACTTGGCCGATACGGACAAGAGTTTTACGCAAATTAATC
TCCACTACAGCAAGCACTTATCATAGGTTGTGATT
>Rosalind_9189
AGAGACGGTAACATTCTCCCCCCGGCCTGTTCTAACCGCCAAATGCCCCGAGGTCGACTG
ATGCCAGGCGCTATCAGGGGCCCATATGCCGCTACATAACGAGTGAATAGGATCCATTAA
ATCGTCCTCCCCCGGTATGTACTCATAAGGCACTTTGAAGGCTAGCTCACATTCTAACGA
GAGGTCGAGATACCGCGTTTAACCAGGTTAGGATCCACCGTATACAGTTCGTAGGAATAA
GTTGATGCTCGGAAAGTAACCGCAACCTGCACTCTTGCGGAAGCGGTCCTAGGCAGGATG
CATAATACGCACAACCGACATGGTCCTACTTTGTTCTCTCTACCGCGGTTGAATGGACTG
GACGCCGTCCCCTGGACAGTATGAATAGCGGGCCGCACAGGCTGATGGTAACGGTGCCCT
GAGGCAACATATATCTTGTTGACCTTGTGAGCTCGGAGCGAGCTTATCTCGGCCACCGTG
GAGTAGTCCTCGCGCGACCATGCTTCGCCCCGAGACAGGAGTTGCTAGTGGTAGCTGCAA
ACTAGTCGGCTTAAAGGCTAAAGATAGTATACCACTGTTTCCCATCATAATGCTCAAGTG
CGCCACACTTTTCTGAAGAACTTTGGTCCCACTGTTTCGGTTGCTGTAGACACGTGAGTA
CCCAACTAGGTAGCCCATCACTGAGGCGGCGCGGATATATTCGTGGGGCATGTCGGGGGG
GGTACCAGCTGCCATAATCATATTGAGTTTCTACACTTTCGGCTTTATGGAACGTCGATG
CTTGCGGTTACGTCTTGCCTTGTGACTTTTTTGCTTCATGTCCCACGAATCCAATTGTCT
GTGGCGGCGTTCCCATAAATCAACTATT
>Rosalind_9495
CACAACCTTACAAACTAGCAACCGGAACCCTTTGGGAATAGTAGGTCGACCGTTAGGCAT
GGCCTGATTCATTTATATAAAGGCGTACCTTGCACGTTAGGGTGGTATACCGATTGGTAT
AGCCACTCCCGAACGTTGACTACCATCGAGGGTGTGCTCCACCGGCGAGTTGTACTGAAT
ACGTCGGAACACTTCTTACCTCTTGCCTACACACCTCGCTATTGGCGATTTCTAATCTAC
GATCTCTTACTGGTAAGAACTTACATTGCAAGCGCGCGTGGTTGCGTTCTAGGTAGTACA
TAGAGCCTTAGAGTGCATTGGCATAAACCCGTATGGTTGAAAAAACTAATTTTGATTATG
TAGTGTGACAACCCATGACCAAATTTTATCGCTACGCGATGCTTGTGAAATACAATACCC
AGTTTCTGTACATGAAATCGCCGGTCGTAGGGATGTTCAAACCGCCACATAGTAAGATAG
CCGCTCGGCTGAAGGACTAGGCCGCGGGAGAAAACGCGTTCTATAGCCACACTGAATAAT
TGTTCGTCCTGCTGTTTTGCGGTTGATTTCCTATCCCTCGATCTACAAGCATTCTCTAAC
TATCCAGATGGTTGAACGAGCCCACCCAATCTTTACTCGTTATTGGTACTGCAGCCCCTC
CCTTCCGGTGGGTGCATGTCGGGGCCGCGGTTTTCTCATCTGAATGGCAGTCCGGCAAGA
ATGACTACCACCCTTGCCATCAGCCGGGATAACAATTGGTGTTGGATCCAGGATTTGGTC
GTGGTGCAGCGGGCAGGCGTCGGAATCTCTTTCAGGTGGCAGCAAGGGCACCAAAAATGG
ATACTTCCGTGTGTGTG
>Rosalind_5170
AATTTACCAGTACCGCGGAAGATGACGTGATCTTCATCATATTTGGACTCGGCTGGCGGA
TTACGTTTCACCGCGTATTTGTCGTATGGCCTATAACGCGGACGCAGGTCTGTGCCCACC
CCACAAGCAAAATTTTCTGTACTGGCAGCGTGAAAGGAGCAGACCTGTTTACCGGGTACC
GAGGCGGAAGCCTTGCCATCGTCAGGTACCCCTAGGGATCCGACTTAAAGGCAAGACTGC
CCCTATACTTATGCTGACTACGGTGCAATCTTGTGTTCTAGGTTTGGGCCGAACCCGCTG
CGTTTCAACGACGATCTGCGCCGCTTAATTGCATAACGGTCCAATCACAATTAAGTTTCC
GGTAGGAGCACTGCTTCTACTGTAGCCCTACAGTTCTTATAGTATTCTCCAGTTTTTGGC
ACAAACCTGGCCAGCGGAGCTGTCGTCTCCAGGAAACTAGTGAAGGGGCTCACGCACCAT
GGCGATCATTTGGTTTTGAAAGGAGTGAGCTAAAGTGTACGCGCCGATCGTATCTTCGCC
ATCGGGGAATTTAGCAATGACTACCCTGCTTGCTAGAATTCAGCGGTCTCTCTGACTAGT
AACGAGGCGATAGGGTTCTTTTCGAGCCTTCCCCTCGAAATTGAACTAACACTGTCGGGC
TGAACAGAGCGAATGAGTGGACGCCACTTGCATCGGTCTGCCATTTGCAAAACTGTATAA
CGAGCCGTACTCGGGCATCCCGTCACGATCGTTTGACTCCGCCGCTTAGTTCCACTCGCC
CCCGTTGCCGAAGGGGTCGTCCCATCACCCATCCCACACCGAGGATCACATCCGCTACAG
TAAGTTAAAGGCGCTTGACACCTGTGGCGAGGCTCACTCGTATTCAATACGATTCAAATT
GCATTTCGGTAAATTGTGGGCCCAGTACCATTTCTGACTGTG
>Rosalind_6411
TCTAAGACATTAAATCAATAGAGAATCAACCGTGTCCTGTTGTCTAGAACTCAAGCCCAA
TTATTTGCCGGCAACGGGGATACCCTGCTACCTTTATGAGGACCCGGGGCGGATCCGTAA
CAGTCTCGATGGGGTGCAGTCCTAATAGTCGGAGAAAAGACCGTCATGCTCGTTGAGACT
CAGACAATTAAATGGCTGCAGACGCTCGTCTTACACAGATCACGAACTTGAACAAGTCCT
CAGCTACTCGTATTATAAGGTCTGTTCCTGAAACCGTACGCGTACTCTCACTCCTTATTT
ACCATCAGAGAAGGCCGCCTACGCGCAATCCTAGCCTCCGCCAACATGGCCCCACAGAGG
ACTGCTGAAGGAAAGTTAAATGTACCCACGGCAGGCGTAAGATAGTGGACAATAGGAAGA
TCCTTAGCCGACCTGAACTCTTCTTTCGATGTATATGGCATCGGTAGTAACAGTCAAGGA
CAATTCAAATTTCATCATGTAGACCATGTAGAGGAGCGAAGTAGAGAGATCTAAAGCATC
GTAACCAGGGGGAGGGGGTGAAACTTAGCTTTCTCCAGAGCACCGGCTACACGGAAGCAT
CGAGGTACGGGAAAAACAGGGTATGCACGCTCTTGTACGCCATTTATTGTTGATATACGG
CTACCGAGGTGTTTACGCTTGCAACCAGTCGGCGGTTCGAGTCACCAGCCGATCTCCACT
GGGGCGCGTCCCTTCTCGATCCCATGACCTTGTAGGACTTAGATGGGTTGTCCCACCTAG
AAAGTCGTCTTAGTGGTAGTCACTCCCAGTACGTACCGGCGGCCAGTATTGCCTGGAAAA
GCACGCGGCCTGGCTGCTGGGGCTTTCTCTTTTGAATGACTTAGGTGGATTGCGTCCCAA
CTGACCACCCTTGCTCCGCCTATTTCGAACACAGCCCTACAAATAATGAAGCCACTGGAG
TGCATTGGCTCCTTGGCGGGAAGAGC
>Rosalind_0030
AGATTAACTCGAGCCCTTCATATTGAGCGAGAAGGAATCCGACCCATGCCGGCCTAATTT
AGCCAGACAGGAAGGAGACAAAATTTTCTATTTTCTAGCAGACTATATCTATGAGGCGGG
GTTACACGCCTTATTTTATGTTAAAATCCATTGCATTTAGGTTAGCTGCGTACTAAAGAC
CAAGAGGTTCCTATCCATGTGACGGGTGAAAAGTAGCGGAAAGCACAGGCACTTGCCCTA
TAGGAAGAAATGACTCAGGCTTCGAGATCTCGTATAAACTTTGCAGGGTATCTCGATCCG
AGCTCTCAGAGTTACCCCGATGGGTAGAGACCGGCCCACGTATAGTTTATCATGCCATTA
TCGTTTTGTGATTCCACACGATACAGATCGGGGAAATAGGGTGTCGCTGGCAAGCAATAG
GCGATTGCCCGGGATCATTCGCCTCGGTCTACTGCCCAAAGATAGCAGTCGTATAAAGTC
TGCTGGCAAAGCCCAGCGCGAGCTAACTTGCAAACGGAGGAAGATGTTTCGTGACATCTG
CCTTCTGAATGCTCTTTTATTGTCACTCGTTGGTTAGTGGGACTCTCGGCGTCAGAGTGT
CCCACGCGGATCGTCCGCAGTGTTGCTAGAGAGTAAATGGGACGTGCGTTTAGTCCTGGT
GACAGTTGGCTCACCCCCCATTTTGTAGAGCCCCGAAAACGACTAGGTAGCTCCCCCAAT
GCGGTATTAGGGAGGCAAACAAAGAACAACTGTTATTTTCGCAGACGGATAAGTTGCCCT
TGGCTATTGCGAATCATCGCTGCTGCGTACCTGAATCATGATCCAAGT
"""
    
    # Function call
    result_id, result_percentage = solve_fasta(dataset)
    
    # Output print karo
    print(result_id)
    print(f"{result_percentage:.6f}")